### ISSUE TITLE
Update to Latest Twilio Voice SDKs

### ISSUE THREAD

**Issue by jefflinwood** [jefflinwood/cordova-plugin-twiliovoicesdk#71]
Android - Version 3
iOS - Version 5

https://github.com/jefflinwood/cordova-plugin-twiliovoicesdk/pull/68

**Comment by rahulmer** [comment]
Dear Jeff,

We recently updated the plugin in our app and when we are using the old framework
https://media.twiliocdn.com/sdk/ios/voice/releases/2.0.1/twilio-voice-ios-2.0.1.tar.bz2
We manage to receive the incoming call (When app is "set state foreground") But when its in background the callkit is not activating.

We then updated the TwilioVoice.framework to 
https://www.twilio.com/docs/voice/voip-sdk/ios

and app started giving this error
![19a4aade202052142456251](https://user-images.githubusercontent.com/31301360/82531142-66aafd80-9b5c-11ea-87b6-a613908f2d63.png)

Can you suggest a fix for receiving incoming call when app in background.

Thanks in advance.

Rahul

**Comment by jefflinwood** [comment]
Work on Twilio Voice 5/iOS 13 is in this branch: https://github.com/jefflinwood/cordova-plugin-twiliovoicesdk/tree/update-voice-ios

**Comment by rahulmer** [comment]
You are great @jefflinwood , Thanks for the fast help!
Its working perfect now :)

**Comment by rahulmer** [comment]
Dear Jeff,
Hope you are good.
The Twilio Voice 5 with iOS 13.7 is not receiving calls when app is not running in background, but when we open the app it do receive the call notification.

Also Twilio wants us to upgrade it to Twilio Voice 5.5.1 and iOS 14, where we are facing issues with both incoming and outgoing call

see below error

`2020-09-21 12:03:21.036138+0530 Link[687:74051] [Snapshotting] Snapshotting a view (0x10400a200, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
2020-09-21 12:03:29.585691+0530 Link[687:74051] Received Incoming Push Payload for VOIP: {
    aps =     {
    };
    "twi_account_sid" = AC0ae825e52aa100c3282d35d4b181be9c;
    "twi_bridge_token" = "eyJ6aXAiOiJERUYiLCJraWQiOiJTQVNfUzNfX19LTVNfdjEiLCJjdHkiOiJ0d2lsaW8tZnBhO3Y9MSIsImVuYyI6IkEyNTZHQ00iLCJhbGciOiJkaXIifQ..7gvK9XWr8Dm7BNvG.LjH7vUHGm_beo8K19xRlJsjSkNI9KJPHEZueSTkuYn0hZPGXdEUxKm04IE14lAO3iasKhGALCMOVKfqbKn1u8l-NKdht7xeAzLCOzIPXBUaSTczunYaW4Ohz7QXQ6oc4TzbeapRC8H0AvdRpy590KMRs3eJEZByyJozRrKxz7YQHLDWfxoPEMhvJyDFVkOUebwH-r7K_RahlWOTSWXgPNvg7KR2A9J47Vd1-nK_bxCOfuSfaK8M6HFC5A8WTQFfxzdy8nJw_205--Ecdr4D5JF5tRrKb9PO_BhIXrwyG1I3e7EHb5Zyffy1OTDqCSHE3rTsVg7rO7c00SfNxFm4v0OkbMwHyZek0yEZqmuHH_d2yrZV9NLA6n51nCWiHz3yg8ipGAuHhSK7Dop5GGXBa_qSql_qVPTIhUKUrWBi5DIvEa2cFr0e04rwnmQfWeaN0W1t2L07DJOX6ac9Rva2I3q2Xdc_3y8RzMVpJ1foUlbKzvLGunZ_d03QQ9u-Jrt7pPLNBCOQWVpVmOSI75iP7e5dD.kCjbvIhUaRcSo7Pt8y5Ceg";
    "twi_call_sid" = CA929db0003df226220959521c629108d3;
    "twi_from" = "+919214433123";
    "twi_message_id" = RUdfad6cf92e36a5d99b1dfb2973f2e38c;
    "twi_message_type" = "twilio.voice.call";
    "twi_to" = "client:rahulmerbascrmcom";
}
2020-09-21 12:03:29.586835+0530 Link[687:74051] +[TwilioVoice handleNotification:delegate:]: unrecognized selector sent to class 0x103789bb8
2020-09-21 12:03:29.587076+0530 Link[687:74051] * Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[TwilioVoice handleNotification:delegate:]: unrecognized selector sent to class 0x103789bb8'
* First throw call stack:
(0x1b58c5344 0x1b55dacc0 0x1b57c8d70 0x1b58c9b20 0x1b58cbe10 0x1028d0ffc 0x1ca0509a0 0x103b0e05c 0x103b0f4d8 0x103b1df64 0x1b58408d4 0x1b583b58c 0x1b583abc8 0x1bfc235cc 0x1b99ed744 0x10289fed8 0x1b56b7384)
libc++abi.dylib: terminating with uncaught exception of type NSException`

not sure if this is regarding you need to fix anything in the plugin or Twilio, but the app is crashing as soon as the call invite came or if we do a outgoing call, please help us to fix it.

Regards
Rahul Mer

**Comment by jefflinwood** [comment]
Hi! I updated the project to use Twilio Voice 5.5.1, and then to use Cocoapods for library installation. I'm going to close this issue out for now.

**Comment by rahulmer** [comment]
Dear Jeff,

The updates are working with incoming calls but for outbound calls its giving error and crashing the application.
Can you please help!

Rahul

**Comment by rahulserver** [comment]
Its crashing for me too on iOS. I'll open a new ticket for that issue.
